keys: 
  - &logan age1ml0hqhru4u2wu6dcwh32ja82sz3nvnuq4ygwpwaar9rkmzzcnvvqrh9e6z
  - &node_loganthinkbook age1pds0seq44wzxpmsly8zt58xuqcmux5r83zhczrwnvnk8rvtry5qspkr0da
  - &node_oraclevps age10mmynej4ulh2prn9hjhuckzsgjxeqv5hupl6htzcrfgk2hju7fksl86tpq
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *logan
  - path_regex: secrets/oracle/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *logan
          - *node_oraclevps
